name: Compile proto files

on:
  workflow_dispatch:
    inputs:
      compile_python:
        required: true
        type: boolean
        description: 'python compiling'
        
      compile_php:
        required: true
        type: boolean
        description: 'php compiling'
        
      compile_java:
        required: true
        type: boolean
        description: 'java compiling'
        
      commit_python:
        required: true
        type: boolean
        description: 'python committing'
        
      commit_php:
        required: true
        type: boolean
        description: 'php committing'
        
      commit_java:
        required: true
        type: boolean
        description: 'java committing'

jobs:
  Python:
    if: ${{ github.event.inputs.compile_python == 'true' }}
    name: Compile proto files to python source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          pip install grpcio grpcio-tools

      - name: Compile
        run: |
          python compile.py python

      - name: Tree
        run: |
          tree

      - name: Commit and Push Changes
        if: ${{ github.event.inputs.commit_python == 'true' }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "compile: proto files compiled"
          git push

  Php:
    if: ${{ github.event.inputs.compile_php == 'true' }}
    name: Compile proto files to php source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: |
          protoc --proto_path=xray_api --php_out=dist/php --grpc_out=dist/php --plugin=protoc-gen-grpc=$(which grpc_php_plugin) $(find xray_api -name '*.proto')

      - name: Tree
        run: |
          tree

      - name: Commit and Push Changes
        if: ${{ github.event.inputs.commit_php == 'true' }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "compile: proto files compiled"
          git push

  Java:
    if: ${{ github.event.inputs.compile_java == 'true' }}
    name: Compile proto files to java source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: |
          protoc --proto_path=xray_api --java_out=dist/java --grpc_out=dist/java --plugin=protoc-gen-grpc-java=$(which protoc-gen-grpc-java) $(find xray_api -name '*.proto')

      - name: Tree
        run: |
          tree

      - name: Commit and Push Changes
        if: ${{ github.event.inputs.commit_java == 'true' }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "compile: proto files compiled"
          git push
